@prefix do: <http://linkedcontainers.org/vocab#> .
@prefix ex: <http://www.example.com#> .
@prefix fno: <https://w3id.org/function/ontology#> .
@prefix fnoc: <https://w3id.org/function/vocabulary/composition#> .
@prefix fnoi: <https://w3id.org/function/vocabulary/implementation#> .
@prefix fnom: <https://w3id.org/function/vocabulary/mapping#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:simple5797f5aaComposition a fno:Composition ;
    fnoc:composedOf [ fnoc:mapFrom [ fnoc:constituentFunction ex:run_2 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_3 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:entrypoint_1 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:cmd_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:run_3 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:workdir_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:from_1 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFromTerm "python3" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:entrypoint_1 ;
                    fnoc:functionParameter do:entrypointInputCommand ] ],
        [ fnoc:mapFromTerm "run.py" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:entrypoint_1 ;
                    fnoc:functionParameter do:entrypointInputParamList ;
                    fnoc:key 0 ;
                    fnoc:mappingStrategy fnoc:toList ] ],
        [ fnoc:mapFromTerm "3" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:cmd_1 ;
                    fnoc:functionParameter do:cmdInputParamList ;
                    fnoc:key 3 ;
                    fnoc:mappingStrategy fnoc:toList ] ],
        [ fnoc:mapFromTerm "." ;
            fnoc:mapTo [ fnoc:constituentFunction ex:copy_1 ;
                    fnoc:functionParameter do:copyDest ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:workdir_1 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:copy_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFromTerm "apt-get install -y python3-pip" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_3 ;
                    fnoc:functionParameter do:runInputCommand ] ],
        [ fnoc:mapFromTerm "2" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:cmd_1 ;
                    fnoc:functionParameter do:cmdInputParamList ;
                    fnoc:key 3 ;
                    fnoc:mappingStrategy fnoc:toList ] ],
        [ fnoc:mapFromTerm "1" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:cmd_1 ;
                    fnoc:functionParameter do:cmdInputParamList ;
                    fnoc:key 3 ;
                    fnoc:mappingStrategy fnoc:toList ] ],
        [ fnoc:mapFromTerm "apt-get update" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_1 ;
                    fnoc:functionParameter do:runInputCommand ] ],
        [ fnoc:mapFromTerm "ubuntu:20.04" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:from_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFromTerm "find . -type f -exec chmod 0744 {} \\;" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_4 ;
                    fnoc:functionParameter do:runInputCommand ] ],
        [ fnoc:mapFromTerm "." ;
            fnoc:mapTo [ fnoc:constituentFunction ex:copy_1 ;
                    fnoc:functionParameter do:copySrc ] ],
        [ fnoc:mapFromTerm "apt-get install -y python3" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_2 ;
                    fnoc:functionParameter do:runInputCommand ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:run_1 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_2 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:run_4 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:entrypoint_1 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFromTerm "/home" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:workdir_1 ;
                    fnoc:functionParameter do:workdirInput ] ],
        [ fnoc:mapFrom [ fnoc:constituentFunction ex:copy_1 ;
                    fnoc:functionOutput do:imageOutputParam ] ;
            fnoc:mapTo [ fnoc:constituentFunction ex:run_4 ;
                    fnoc:functionParameter do:imageInputParam ] ],
        [ fnoc:mapFromTerm "4" ;
            fnoc:mapTo [ fnoc:constituentFunction ex:cmd_1 ;
                    fnoc:functionParameter do:cmdInputParamList ;
                    fnoc:key 3 ;
                    fnoc:mappingStrategy fnoc:toList ] ] ;
    fnoc:represents ex:simple5797f5aa ;
    fnoc:start ex:from_1 .

ex:simple5797f5aaMapping a fno:Mapping ;
    fno:function ex:simple5797f5aa ;
    fno:implementation ex:simple5797f5aaDockerfileImplementation ;
    fno:returnMapping [ a fnom:DefaultReturnMapping ;
            fnom:functionOutput do:ImageOutput ] ;
    fnom:mappingMethod "default" .

do:cmd a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ;
            rdf:_3 do:cmdInputParamList ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

do:copy a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ;
            rdf:_2 do:copySrc ;
            rdf:_3 do:copyDest ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

do:entrypoint a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ;
            rdf:_2 do:entrypointInputCommand ;
            rdf:_3 do:entrypointInputParamList ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

do:from a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

do:workdir a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ;
            rdf:_2 do:workdirInput ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

ex:simple5797f5aaDockerfileImplementation a do:Dockerfile,
        fnoi:Dockerfile ;
    fnoi:file <file:///home/ponachte/projects/py2rdf/docker_examples/simple/Dockerfile> .

do:ImageOutput a fno:Output ;
    fno:predicate ex:outputImage ;
    fno:type do:Image .

do:copyDest a fno:Parameter ;
    fno:predicate do:dest ;
    fno:type xsd:String .

do:copySrc a fno:Parameter ;
    fno:predicate do:src ;
    fno:type xsd:String .

do:entrypointInputCommand a fno:Parameter ;
    fno:predicate do:entrypointCMD ;
    fno:type do:Command .

do:entrypointInputParamList a fno:Parameter ;
    fno:predicate do:entrypointCMDParams ;
    fno:type do:Param .

do:workdirInput a fno:Parameter ;
    fno:predicate do:directory ;
    fno:type xsd:String .

ex:simple5797f5aa a do:Dockerfile,
        prov:Entity,
        fno:Function ;
    fno:expects [ a rdf:Seq ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:ImageOutput ] .

ex:from_1 fnoc:applies do:from ;
    fnoc:next ex:run_1 .

do:run a do:Instruction,
        fno:Function ;
    fno:expects [ a rdf:Seq ;
            rdf:_1 do:imageInputParam ;
            rdf:_2 do:runInputCommand ] ;
    fno:returns [ a rdf:Seq ;
            rdf:_1 do:imageOutputParam ] .

ex:run_1 fnoc:applies do:run ;
    fnoc:next ex:run_2 .

ex:run_2 fnoc:applies do:run ;
    fnoc:next ex:run_3 .

ex:run_3 fnoc:applies do:run ;
    fnoc:next ex:workdir_1 .

ex:run_4 fnoc:applies do:run ;
    fnoc:next ex:entrypoint_1 .

ex:workdir_1 fnoc:applies do:workdir ;
    fnoc:next ex:copy_1 .

do:cmdInputParamList a fno:Parameter ;
    fno:predicate do:cmdParams ;
    fno:type do:Param .

do:runInputCommand a fno:Parameter ;
    fno:predicate do:runCmd ;
    fno:type do:Command .

ex:copy_1 fnoc:applies do:copy ;
    fnoc:next ex:run_4 .

ex:entrypoint_1 fnoc:applies do:entrypoint ;
    fnoc:next ex:cmd_1 .

ex:cmd_1 fnoc:applies do:cmd .

do:imageOutputParam a fno:Output ;
    fno:predicate do:imageOutput ;
    fno:type do:Image .

do:imageInputParam a fno:Parameter ;
    fno:predicate do:imageInput ;
    fno:type do:Image .

